![Hand with calculator](calculator.png "Calculator")

Did you know that the average return from investing in stocks is 10% per year! But who wants to be average?! 

You have been asked to support an investment firm by analyzing trends in high-growth companies. They are interested in understanding which industries are producing the highest valuations and the rate at which new high-value companies are emerging. Providing them with this information gives them a competitive insight as to industry trends and how they should structure their portfolio looking forward.

You have been given access to their `unicorns` database, which contains the following tables:

`dates`
| Column       | Description                                  |
|------------- |--------------------------------------------- |
| company_id   | A unique ID for the company.                 |
| date_joined  | The date that the company became a unicorn.  |
| year_founded | The year that the company was founded.       |

`funding`
| Column           | Description                                  |
|----------------- |--------------------------------------------- |
| company_id       | A unique ID for the company.                 |
| valuation        | Company value in US dollars.                 |
| funding          | The amount of funding raised in US dollars.  |
| select_investors | A list of key investors in the company.      |

`industries`
| Column       | Description                                  |
|------------- |--------------------------------------------- |
| company_id   | A unique ID for the company.                 |
| industry     | The industry that the company operates in.   |

`companies`
| Column       | Description                                       |
|------------- |-------------------------------------------------- |
| company_id   | A unique ID for the company.                      |
| company      | The name of the company.                          |
| city         | The city where the company is headquartered.      |
| country      | The country where the company is headquartered.   |
| continent    | The continent where the company is headquartered. |

The task for this unguided SQL project was to identify the trends in the three best-performing industries based on the number of new unicorns created over the last three years (2019, 2020, and 2021) combined.

The following SQL query was implemented and the top performing industries were:
1. E-commerce & direct-to-consumer
2. Fintech
3. Internet software and services

In [18]:
-- Creating a CTE called TOP3 to identiify the top 3 industries for the number of unicorns created from 2019-2021 combined
WITH TOP3 AS (SELECT industry,
       COUNT(*) AS num_unicorns
FROM industries
INNER JOIN dates
ON industries.company_id = dates.company_id
WHERE EXTRACT(year FROM date_joined) BETWEEN 2019 AND 2021
GROUP BY industry
ORDER BY num_unicorns DESC
LIMIT 3)

-- Querying the tables for the top 3 industries identified in the TOP3 CTE
SELECT industry,
EXTRACT(year FROM date_joined) AS year,
COUNT(*) AS num_unicorns,
ROUND(AVG(valuation / 1000000000), 2) AS average_valuation_billions  --Calculating average valuation in billions
FROM industries
INNER JOIN dates
ON industries.company_id = dates.company_id
INNER JOIN funding
ON dates.company_id = funding.company_id
WHERE industry in (SELECT industry FROM TOP3)  -- Selecting only the top 3 industries identified in the CTE
AND EXTRACT(year FROM date_joined) BETWEEN 2019 AND 2021
GROUP BY industry, year
ORDER BY industry, year DESC; -- Displaying the trends for the top 3 industries

,industry,year,num_unicorns,average_valuation_billions
0,E-commerce & direct-to-consumer,2021,47,2.47
1,E-commerce & direct-to-consumer,2020,16,4.00
2,E-commerce & direct-to-consumer,2019,12,2.58
3,Fintech,2021,138,2.75
4,Fintech,2020,15,4.33
5,Fintech,2019,20,6.80
6,Internet software & services,2021,119,2.15
7,Internet software & services,2020,20,4.35
8,Internet software & services,2019,13,4.23